---

- include_vars: "{{ ansible_distribution }}.yml"
  tags: [emonhub]

- name: Install packages needed for emonhub
  sudo: yes
  action: >
    {{ ansible_pkg_mgr }}
    name={{ item }}
    state=present
  with_items: emonhub_ansible_role_distro_vars.emonhub_packages
  tags: [emonhub]

- name: Create non-priviledged user to run emonhub
  sudo: yes
  user: >
    name="{{ emonhub_ansible_role.emonhub_user }}"
    createhome=yes
    append=yes
    groups="{{ emonhub_ansible_role_distro_vars.emonhub_user_groups | join(',') }}"
  tags: [emonhub]

- name: Check if emonhub is already installed
  stat: >
    path={{ emonhub_ansible_role.emonhub_installation_dir }}
  register: emonhub_installation_check
  tags: [emonhub]

- name: Clone emonhub development branch from github
  sudo: yes
  when: emonhub_installation_check.stat.exists == false
  git: >
    repo=https://github.com/emonhub/emonhub.git
    dest={{ emonhub_ansible_role.emonhub_repo_installation_dir }}
    version={{ emonhub_branch | default(development) }}
  tags: [emonhub]

# TODO fakt tezke tady vymyslet nejake jmeno, chce to popisek, dokumentaci
# TODO owner/group muze byt? Asi jo, ale stejne by bylo lepsi mit non-priviledged usera
# TODO nahore uz toho nonroota vyrabim
# Kazdopadne potrebuje sudo, aby si sahl na /dev/ttyATM0
- name: Install emonhub from sources with a symlink
  sudo: yes
  file: >
    src={{ emonhub_ansible_role.emonhub_repo_installation_dir }}/src
    dest={{ emonhub_ansible_role.emonhub_installation_dir }}
    owner=root
    group=root
    state=link
  tags: [emonhub]

- name: Install systemd service for emonhub
  sudo: yes
  template: >
    src=emonhub.service.j2
    dest=/usr/lib/systemd/system/emonhub.service
    owner=root
    group=root
  tags: [emonhub, service]

# the ansible file module not used here to create the logfile
# because with state=file for the file module, the status of the action would
# be "changed" for every run, see doc why
# Thanks to "creates" arg,the logfile is really created only when doesn't exist
- name: Create logfile for emonhub
  command: touch {{ emonhub_ansible_role.emonhub_logfile }}
  args:
    creates: "{{ emonhub_ansible_role.emonhub_logfile }}"
  tags: [emonhub]

- name: Setup emonhub logfile permissions
  sudo: yes
  file: >
    dest={{ emonhub_ansible_role.emonhub_logfile }}
    owner={{ emonhub_ansible_role.emonhub_user }}
    group=users
    state=file
  tags: [emonhub]

# TODO toto tady neni dobry, neni hezke
- name: Create directory in /etc for emonhub configuration
  sudo: yes
  file: >
    dest={{ emonhub_ansible_role.emonhub_config_path }}
    state=directory
  tags: [emonhub]

- name: Deploy emonhub configuration file
  sudo: yes
  template: >
    src=emonhub.conf.j2
    dest={{ emonhub_ansible_role.emonhub_config_path }}/emonhub.conf
    owner=root
    group=root
  tags: [emonhub]

- name: Enable and start emonhub service
  sudo: yes
  service: >
    name=emonhub.service
    enabled=yes
    state=started
  tags: [emonhub]

# TODO logrotate
